### ISSUE TITLE
Generalized response builder

### ISSUE THREAD

**Issue by devmsh** [The-POS/The-POS-Laravel#6]
> @123mousab while we use API Resource, I think no need to do so.
> 
> Can you please give me more details if you think we still need that?

Creating generalized response builder helps to manage complex api structure in a predictable way for the mobile developers, this will be necessary in case you used paginations, status messages, and returning multiple types of data in the same request.

_Originally posted by @ahmdqader in https://github.com/The-POS/The-POS-Laravel/issues/4#issuecomment-939535110_

**Comment by alaa-alsalehi** [comment]
I think this is a reasonable request
and the response suppose to be something like this
```
{
  response: [
  -- REAL RESPONSE ARRAY
  ],
  page: 1, -- current page
  records_count: 10, -- number of records in response
  total: 100 -- the total number of records in this resource
}
```
please check it and let me know if this fit to modify the API specification

**Comment by devmsh** [comment]
@ahmdqader @123mousab waiting from you

@ServeMe we already have a standard response structure that is more mature and give a lot of extra info for the pagination, I already asked for #7 so I can submit the proposed changes for you.

**Comment by alaa-alsalehi** [comment]
OK no problem I add the specification if there is any enhancement here move it to the next version please

**Comment by ahmdqader** [comment]
<img width="337" alt="Screen Shot 2021-10-11 at 4 49 13 PM" src="https://user-images.githubusercontent.com/20671316/136833400-1af31f3f-bdbc-4100-8dfe-0c12416a6949.png">

I find this response structure cleaner and simpler and give you the ability to add extra data as you like.

<img width="343" alt="Screen Shot 2021-10-11 at 9 02 33 PM" src="https://user-images.githubusercontent.com/20671316/136834664-7ab0052a-b56e-48e3-9395-c779430749cc.png">

we can also add the links to pagination section.

**Comment by alaa-alsalehi** [comment]
I think there is no need for this HTTP 200 has the same meaning
